import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackClientApp } from "../stack/client";
import { Geist_Mono, Outfit, Merriweather } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { navigationData } from "@/lib/utils";
import Footer from "@/components/Footer";

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-sans",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  variable: "--font-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Storefront",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} ${outfit.variable} ${merriweather.variable} antialiased`}
      >
        <Analytics />
        <SpeedInsights />
        <StackProvider app={stackClientApp}>
          <StackTheme>
            <Navbar navigationData={navigationData} />
            {children}
          </StackTheme>
        </StackProvider>
        <Footer />
      </body>
    </html>
  );
}
